# Generated by Django 5.1.3 on 2024-11-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='freelancer_platform_app.offer'),
        ),
    ]
