# Generated by Django 5.1.3 on 2024-11-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0003_remove_order_business_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_detail',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='freelancer_platform_app.offerdetail'),
            preserve_default=False,
        ),
    ]
