# 
# 
# Description
# 
# This file can be used to send HTTP-Requests and view the response in Visual Studio Code directly.
# Install Rest-Client Extension for Visual Studio Code to use this test-file:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# 
# 
# Usage
# 
# Enter a valid {@token} and hit the 'Send-Request'-button above the request with the django-server running.
# The 'registration/'- and 'login/'-endpoints do not require a token.
# The response will be previewed in a separate webview panel of Visual Studio Code.
# The {name}.rest files contain various requests, that were used for Testing during Development.
# You can alter the requests or create new ones to test all kinds of situations.
# 
# 
# Token
# 
# Some requests require a valid API-Token.
# You will get a token by sending a POST-request to the 'registration/'-endpoint with valid credentials.
# You can use the first request of the auth.rest file in the auth_app-folder.
# Just replace the value of the @token-variable below with the token of the response.
# 
# 
# Caution
# 
# Keep in mind, that these are real requests and there is no test database.
# The requests will alter the data of the projects database.
# 
# 


@token_business = dcfb5de69a0690bb60bd75bc4eee218aa45f72ee
@token_customer = d80002f692d744e5b98fbfc9b148072cec6b1876
@token_admin = 66951446c4e912903de88fe344981606db14cf92
### AUTH ###


POST http://127.0.0.1:8000/api/registration/
Content-Type: application/json

{ "username": "user-business", "email": "user-business@mail.de", "password": "123456789", "repeated_password": "123456789", "type": "business" }

###

POST http://127.0.0.1:8000/api/registration/
Content-Type: application/json

{ "username": "user-customer", "email": "user-customer@mail.de", "password": "123456789", "repeated_password": "123456789", "type": "customer" }


###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{ "username": "user-customer", "password": "123456789" }

###

GET http://127.0.0.1:8000/api/profile/1
Content-Type: application/json
Authorization: token {{token_customer}}

###

PATCH http://127.0.0.1:8000/api/profile/1/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "first_name": "Andrey",
    "last_name": "Kaufmann",
    "email": "andreyk@gast.de",
    "tel": "063541630",
    "location": "Berlin",
    "description": "Die Firma",
    "working_hours": 40
}

###

PATCH http://127.0.0.1:8000/api/profile/6/
Content-Type: application/json
Authorization: token {{token_business}}

{
    "first_name": "Kevin",
    "last_name": "Theisen",
    "email": "kevint@gast.de",
    "tel": "063541630",
    "location": "Berlin",
    "description": "Die Firma",
    "working_hours": 40
}

###

PATCH http://127.0.0.1:8000/api/profile/2/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "first_name": "User",
    "last_name": "Business",
    "email": "user-business@mail.de",
    "tel": "016077777777",
    "location": "Koblenz",
    "description": "User Business Firma",
    "working_hours": 60
}

###

GET http://127.0.0.1:8000/api/profiles/customer
Content-Type: application/json
Authorization: token {{token_customer}}

###

GET http://127.0.0.1:8000/api/profiles/business
Content-Type: application/json
Authorization: token {{token_customer}}