# 
# 
# Description
# 
# This file can be used to send HTTP-Requests and view the response in Visual Studio Code directly.
# Install Rest-Client Extension for Visual Studio Code to use this test-file:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# 
# 
# Usage
# 
# Enter a valid {@token} and hit the 'Send-Request'-button above the request with the django-server running.
# The 'registration/'- and 'login/'-endpoints do not require a token.
# The response will be previewed in a separate webview panel of Visual Studio Code.
# The {name}.rest files contain various requests, that were used for Testing during Development.
# You can alter the requests or create new ones to test all kinds of situations.
# 
# 
# Token
# 
# Some requests require a valid API-Token.
# You will get a token by sending a POST-request to the 'registration/'-endpoint with valid credentials.
# You can use the first request of the auth.rest file in the auth_app-folder.
# Just replace the value of the @token-variable below with the token of the response.
# 
# 
# Caution
# 
# Keep in mind, that these are real requests and there is no test database.
# The requests will alter the data of the projects database.
# 
# 


@token_business = 62800b6b806b7a6837b953e0d73256561a978b24
@token_customer = caef84cccc6627c2ae0c71c5d3b8655252b86a01
@token_admin = 66951446c4e912903de88fe344981606db14cf92

### Orders

GET http://127.0.0.1:8000/api/orders/
Content-Type: application/json
Authorization: token {{token_business}}

###

GET http://127.0.0.1:8000/api/orders/3
Content-Type: application/json
Authorization: token {{token_business}}

###

POST http://127.0.0.1:8000/api/orders/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "offer_detail_id": 21
}

###

PATCH http://127.0.0.1:8000/api/orders/13/
Content-Type: application/json
Authorization: token {{token_business}}

{
    "status": "completed"
}

###

DELETE http://127.0.0.1:8000/api/orders/13/
Content-Type: application/json
Authorization: token {{token_admin}}

{
    "status": "completed"
}