# 
# 
# Description
# 
# This file can be used to send HTTP-Requests and view the response in Visual Studio Code directly.
# Install Rest-Client Extension for Visual Studio Code to use this test-file:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# 
# 
# Usage
# 
# Enter a valid {@token} and hit the 'Send-Request'-button above the request with the django-server running.
# The 'registration/'- and 'login/'-endpoints do not require a token.
# The response will be previewed in a separate webview panel of Visual Studio Code.
# The {name}.rest files contain various requests, that were used for Testing during Development.
# You can alter the requests or create new ones to test all kinds of situations.
# 
# 
# Token
# 
# Some requests require a valid API-Token.
# You will get a token by sending a POST-request to the 'registration/'-endpoint with valid credentials.
# You can use the first request of the auth.rest file in the auth_app-folder.
# Just replace the value of the @token-variable below with the token of the response.
# 
# 
# Caution
# 
# Keep in mind, that these are real requests and there is no test database.
# The requests will alter the data of the projects database.
# 
# 


@token_business = dcfb5de69a0690bb60bd75bc4eee218aa45f72ee
@token_customer = d80002f692d744e5b98fbfc9b148072cec6b1876
@token_admin = 88b762f73eb663ce65037bbc19d69bdf8651c7ab
### Reviews 

GET http://127.0.0.1:8000/api/reviews/
Content-Type: application/json
Authorization: token {{token_customer}}

###

GET http://127.0.0.1:8000/api/reviews/3
Content-Type: application/json
Authorization: token {{token_customer}}

###

POST http://127.0.0.1:8000/api/reviews/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "business_user": 19,
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

POST http://127.0.0.1:8000/api/reviews/
Content-Type: application/json
Authorization: token {{token_business}}

{
    "business_user": 3,
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

PATCH http://127.0.0.1:8000/api/reviews/11/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

PATCH http://127.0.0.1:8000/api/reviews/5/
Content-Type: application/json
Authorization: token {{token_business}}

{
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

PATCH http://127.0.0.1:8000/api/reviews/10/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

PATCH http://127.0.0.1:8000/api/reviews/200/
Content-Type: application/json
Authorization: token {{token_customer}}

{
    "rating": 5,
    "description": "Hervorragende Erfahrung!"
}

###

DELETE http://127.0.0.1:8000/api/reviews/200/
Content-Type: application/json
Authorization: token {{token_customer}}

###

DELETE http://127.0.0.1:8000/api/reviews/15/
Content-Type: application/json
Authorization: token {{token_customer}}

###

DELETE http://127.0.0.1:8000/api/reviews/16/
Content-Type: application/json
Authorization: token {{token_business}}